config/routes.rb
Sport::Application.routes.draw do
  get "children/new"

  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :groups # , only: [ :new, :create, :destroy, :edit ]
  resources :children
  resources :affiliations 
  resources :appointments

  root :to => "pages#home"

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy", via: :delete

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/help', :to => "pages#help"
  match '/home', :to => "pages#home"

  match '/newgroup', :to => "groups#new"

end

app/models/group.rb
# -*- coding: utf-8 -*-
class Group < ActiveRecord::Base
  attr_accessible :user_id, :name, :starts_at, :ends_at, :agegroup, :kindergarden, :category, :duration, :intermittency

  belongs_to :user
  has_many :affiliations
  has_many :appointments


  has_many :children, :through => :affiliations

  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }

  default_scope order: 'groups.starts_at DESC NULLS LAST'

  def ag(x)
    case x
      when 1 then "(2-4)"
      when 2 then "(5-6)"
      when 3 then "(7-10)"
      when 4 then "(11-15)"
      when 5 then "(15-16)"
    end
  end

  def king(x)
    case x
      when false then "nein"
      when true then "ja"
    end
  end

  def intm(x)
    case x
      when 1 then "wöchentlich"
      when 2 then "14tägig"
      when 3 then "2x/Woche"
      when 4 then "täglich"
    end
  end

  def cat(x)
    case x
      when 1 then "Kindersport"
      when 2 then "Eltern-Kind-Sport"
      when 3 then "Kinderturnen"
      when 4 then "Turnen/Akrobatik"
      when 5 then "Artistik/Akrobatik"
      when 6 then "Badminton"
    end
  end

  def ingroup?(child)
    affiliations.find_by_child_id(child.id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy, :update]

  def new
    @group = Group.new(:user_id => params[:id])
  end

  def index
    @groups = Group.paginate(page: params[:page], :per_page => 15)
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:success] = "Gruppe angelegt!"
      @group.termseries.each do |t|
        @newapp = Appointment.new(:group_id => @group.id, :date_at => t)
        @newapp.save
      end
      redirect_to User.find(params[:group][:user_id])
    else
      flash[:error] = "Gruppe konnte nicht angelegt werden!"
      redirect_to new_group_path
    end
  end

  def destroy
  end

  def show
    @group = Group.find(params[:id])
    if @group.affiliations.count != 0
      @children = @group.children
    else
      @noc=0
    end
    if @group.appointments.count != 0
      @appointments = @group.appointments
    else
      @noa=0
    end

  end

  def edit
    @group = Group.find(params[:id])
    @appointments = @group.appointments
  end

  def update
    @group = Group.find_by_id(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Gruppeninformationen aktualisiert"
      redirect_to(:back)
    else
      flash[:error] = "Es ist ein Fehler aufgetreten"
      render 'edit'
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
    def termseries(group)
    @dur =  (group.ends_at - group.starts_at).to_int / 7
    @apps = (1..@dur).collect { |x| group.starts_at + (7*x).days } 
    end
end

app/views/groups/_affiliation.html.haml
%tr
  %td= child.child_id

app/views/groups/_child.html.haml
%tr
  %td= @child.id
    

app/views/groups/_editgroup.html.haml
= form_for @group do |f|
  %table
    %tr
      %td{ :min_width => "200px;" }=f.label "Gruppe"
      %td=f.text_field :name
      %td=f.label "Gruppenleiter"
      %td=f.select :user_id, usrlist
    %tr
      %td=f.label "Kindergarten"
      %td=f.select :kindergarden, [["nein",false],["ja",true]]
      %td=f.label "Häufigkeit"
      %td=f.select :intermittency, [["wöchentlich",1],["14tägig",2],["2x/Woche",3],["täglich",4]]
    %tr
      %td=f.label "Beginn"
      %td=f.date_select :starts_at, :start_year => Time.now.year, :end_year => Time.now.year + 1
      %td=f.label "Ende"
      %td=f.date_select :ends_at, :start_year => Time.now.year, :end_year => Time.now.year + 1
    %tr
      %td=f.label "Kategorie"
      %td=f.select :category, [["Kindersport",1],["Eltern-Kind-Sport",2],["Kinderturnen",3],["Turnen/Akrobatik",4],["Artistik/Akrobatik",5],["Badminton",6]]
      %td=f.label "Altersgruppe"
      %td=f.select :agegroup, [["2-4", 1], ["5-6", 2], ["7-10", 3],["11-15",4],["15-16",5]]
    %tr
  = submit_tag 'Speichern', :class => 'btn btn-large btn-primary'

app/views/groups/_group.html.haml
%tr
  %td
    = link_to group.name, group_path(group), :id => group.id
    = link_to "  edit", edit_group_path(group), :id => group.id
  %td{:align => "center"}=group.user.fullname
  %td{:align => "center"}=group.starts_at
  %td{:align => "center"}=group.ends_at
  %td{:align => "center"}=group.ag(group.agegroup)
  %td{:align => "center"}=group.king(group.kindergarden)
  %td{:align => "center"}=group.cat(group.category)
  %td{:align => "center"}=group.duration
  %td{:align => "center"}=group.intm(group.intermittency)
  - if group.starts_at != nil
    %td=time_ago_in_words(group.starts_at)

  

app/views/groups/edit.html.haml
%h1 Gruppeninformationen bearbeiten
%div{ :class => "row" }
  %div
    = render(:partial => "editgroup", :id => :id )
  %div
    %h3 Termine
    %table
      %tr
        %td Datum
        %td entfallen
        %td Grund
        %td Kommentar
      - @appointments.each do |appointment|
        = render appointment
    %br
    %h3 Neuer Termin
    %div
      %div
        %table
          = form_for @group.appointments.build(group_id: @group.id) do |f|
            %tr
              %td
                = f.hidden_field :group_id, :default => @group_id
                = f.label "Datum"
                = f.date_select :date_at, :start_year => Time.now.year, :end_year => Time.now.year + 1, :include_blank => true
            %tr
              %td
                = f.label "ausgefallen"
                = f.select :canceled, [["nein",false],["ja",true]], :default => false
            %tr
              %td
                = f.label "Grund"
                = f.select :reason, [["Feiertag", 1],["Krankheit",2],["anderes",3]], :include_blank => true
            %tr
              %td
                = f.label "Kommentar"
                = f.text_field :comment
                = submit_tag 'Speichern', :class => 'btn btn-large btn-primary'

app/views/groups/index.html.haml
%h1 Gruppenliste
= will_paginate
%table
  %thead
    %td Gruppenname
    %td Gruppenleiter
    %td Start
    %td Ende
    %td Altersgruppe
    %td Kindergarten
    %td Kategorie
    %td Dauer (min)
    %td Intervall
  %body
    - @groups.each do |group|
      = render group
= will_paginate
= link_to "Neue Gruppe anlegen", newgroup_path

app/views/groups/new.html.haml
%h1 Neue Gruppe
%div{ :class => "row" }
  %div
    = render(:partial => "editgroup", :id => @group.id )

app/views/groups/show.html.haml
%h1= "Gruppe: " + @group.name
%div{ :class => "row" }
  %div
    - if @noc.nil?
      %table
        %thead
          %td Vorname
          %td Name
          %td Geburtsdatum
          %td Geschlecht
          %td Postleitzahl
        %body
        - @children.each do |child|
          = render child
    - else
      %p Die Gruppe hat noch keine Teilnehmer
    - if @noa.nil?
      %h3 Termine
      %table
        %tr
          %td Datum
          %td entfallen
          %td Grund
          %td Kommentar
        - @appointments.each do |appointment|
          = render appointment
  