config/routes.rb
Sport::Application.routes.draw do
  get "children/new"

  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :groups # , only: [ :new, :create, :destroy, :edit ]
  resources :children
  resources :affiliations 
  resources :appointments

  root :to => "pages#home"

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy", via: :delete

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/help', :to => "pages#help"
  match '/home', :to => "pages#home"

  match '/newgroup', :to => "groups#new"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :group_id, :date_at, :canceled, :reason, :comment

  belongs_to :group
  has_many :children, :through => :groups
  has_many :attendances

  validates :group_id, presence: true
  validates :date_at, presence: true

end

app/models/appointments.rb
class Appointments < ActiveRecord::Base
  belongs_to :group
  has_many :children, :through => :groups

  validates :group_id, presence: true
  validates :date_at, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ActionController::Base
  layout "application"
  protect_from_forgery
  include GroupsHelper

  def create
  end

  def new
    @appointment = Appointment.new(:group_id => params[:id])
  end

  def create
    @appointment = Appointment.new(params[:appointment])
    if @appointment.save
      @appointment.group.children.each do |child|
        @attendance = Attendance.new(:child_id => child.id, :appointment_id => @appointment.id)
        @attendance.save
      end
      flash[:success] = "Termin angelegt"
    else
      flash[:error] = "Fehler, anlegen nicht moeglich"
    end
    redirect_to(:back)
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

end

app/views/appointments/_appointment.html.haml
%tr
  %td
    = link_to appointment.date_at, appointment_path(appointment)
    = link_to " edit", edit_appointment_path(appointment)
  %td= appointment.canceled
  %td= appointment.reason
  %td= appointment.comment

app/views/appointments/new.html.haml
%h1 Neuen Termin anlegen
%div{ :class => "row" }
  %div{ :class => "span3 offset3" }
    %div{ :class => "newuser" }
      = form_for @appointment do |f|
        = f.hidden_field :group_id, :default => params[:id]
        = f.date_select :date_at, :start_year => Time.now.year, :end_year => Time.now.year + 1, :include_blank => true
        = f.select :canceled, [["nein",false],["ja",true]], :default => false
        = f.select :reason, [["Feiertag", 1],["Krankheit",2],["anderes",3]], :include_blank => true
        = f.text_field :comment
        = submit_tag 'Speichern', :class => 'btn btn-large btn-primary'

app/views/appointments/show.html.haml
%h1= "Termin"
= @appointment.attendances.count
%table
  %tr
    %td Vorname
    %td name
    %td Abwesenheit
    %td Grund
    %td Kommentar
  - @appointment.attendances.each do |attendance|
    %tr
      %td= attendance.child.firstname
      %td= attendance.child.lastname
      %td= attendance.absence
      %td= attendance.reason
      %td= attendance.comment