config/routes.rb
Sport::Application.routes.draw do
  get "children/new"

  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :groups # , only: [ :new, :create, :destroy, :edit ]
  resources :children
  resources :affiliations 
  resources :appointments

  root :to => "pages#home"

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy", via: :delete

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/help', :to => "pages#help"
  match '/home', :to => "pages#home"

  match '/newgroup', :to => "groups#new"

end

app/views/layouts/_footer.html.haml
%footer
  %small
    = link_to "Home", home_path
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Kontakt", contact_path
      %li= link_to 'CrescNet', "http://www.crescnet.org"
      %li= link_to 'Kindersportzentrum', "http://kindersportzentrum.scdhfk.de/"

app/views/layouts/_header.html.haml
%header{ :class => "navbar navbar-fixed-top"}
  %div{ :class => "navbar-inner" }
    %div{ :class => "container" }
    = link_to "Entwurf Sportprojekt", "#", id: "logo"
    %nav
      %ul{ :class => "nav pull-right"}
        %li= link_to "Home", home_path
        %li= link_to "Help", help_path
        - if signed_in?
          %li= link_to "Users", users_path
          %li= link_to "Gruppen", groups_path
          %li= link_to "Kinder", children_path
          %li{ :id => "fat-menu", :class => "dropdown" }
            %a{ :href => "#", :class => "dropdown-toggle", "data-toggle" =>  "dropdown" } 
              Account
              %b{ :class => "caret" }
            %ul{ :class => "dropdown-menu" }
              %li= link_to "Profile", "#"
              %li= link_to "Settings", edit_user_path(current_user)
              %li{ :class => "divider" }
              %li= link_to "LogOut", signout_path, method: "delete"
        - else
          %li= link_to "LogIn", signin_path
       
  

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"
/[if lt IE 9]
  %script{ :src => "http://html5shiv.googlecode.com/svn/trunk/html5.js" }

app/views/layouts/application.html.haml
!!!
%head
  %title= title
  = csrf_meta_tag
  = render :partial => "layouts/stylesheets"
%body
  .container
    = render :partial => "layouts/header"
    %section
      - [:success, :notice, :error, :message].each do |key|
        - unless flash[key].blank?
          %p{ :class => "alert alert-#{key}" }= flash[key]
    .content#content= yield   
    %footer
    = render :partial => "layouts/footer" 
    = debug(params) if Rails.env.development?